"""empty message

Revision ID: 10dc72b15ef8
Revises: 6d1d1736f132
Create Date: 2018-01-02 05:58:52.128795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10dc72b15ef8'
down_revision = '6d1d1736f132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kosts', sa.Column('city_Cid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_kosts_Kaddress'), 'kosts', ['Kaddress'], unique=False)
    op.create_index(op.f('ix_kosts_Kname'), 'kosts', ['Kname'], unique=False)
    op.drop_index('ix_kosts_Kaddress', table_name='kosts')
    op.drop_index('ix_kosts_Kname', table_name='kosts')
    op.create_foreign_key(None, 'kosts', 'cities', ['city_Cid'], ['Cid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kosts', type_='foreignkey')
    op.create_index('ix_kosts_Kname', 'kosts', ['Kname'], unique=False)
    op.create_index('ix_kosts_Kaddress', 'kosts', ['Kaddress'], unique=False)
    op.drop_index(op.f('ix_kosts_Kname'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kaddress'), table_name='kosts')
    op.drop_column('kosts', 'city_Cid')
    # ### end Alembic commands ###
