"""empty message

Revision ID: 118de36b592b
Revises: a847edd6e3a5
Create Date: 2018-01-01 17:26:36.975059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118de36b592b'
down_revision = 'a847edd6e3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kosts', sa.Column('Klat', sa.DECIMAL(precision=10, scale=8), nullable=True))
    op.add_column('kosts', sa.Column('Klng', sa.DECIMAL(precision=11, scale=8), nullable=True))
    op.create_index(op.f('ix_kosts_Kaddress'), 'kosts', ['Kaddress'], unique=False)
    op.create_index(op.f('ix_kosts_Kname'), 'kosts', ['Kname'], unique=False)
    op.drop_index('ix_kosts_Kaddress', table_name='kosts')
    op.drop_index('ix_kosts_Kname', table_name='kosts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_kosts_Kname', 'kosts', ['Kname'], unique=False)
    op.create_index('ix_kosts_Kaddress', 'kosts', ['Kaddress'], unique=False)
    op.drop_index(op.f('ix_kosts_Kname'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kaddress'), table_name='kosts')
    op.drop_column('kosts', 'Klng')
    op.drop_column('kosts', 'Klat')
    # ### end Alembic commands ###
