"""empty message

Revision ID: 292a3c2c3e9c
Revises: b0bdf797d016
Create Date: 2018-06-08 01:59:53.294347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292a3c2c3e9c'
down_revision = 'b0bdf797d016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_kosts_Kaddress'), 'kosts', ['Kaddress'], unique=False)
    op.create_index(op.f('ix_kosts_Kname'), 'kosts', ['Kname'], unique=False)
    op.create_index(op.f('ix_kosts_Kprice_range'), 'kosts', ['Kprice_range'], unique=False)
    op.create_index(op.f('ix_kosts_Kprice'), 'kosts', ['Kprice'], unique=False)
    op.create_index(op.f('ix_kosts_Ktype'), 'kosts', ['Ktype'], unique=False)
    op.drop_index('ix_kosts_Kprice', table_name='kosts')
    op.drop_index('ix_kosts_Kprice_range', table_name='kosts')
    op.drop_index('ix_kosts_Ktype', table_name='kosts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_kosts_Ktype', 'kosts', ['Ktype'], unique=False)
    op.create_index('ix_kosts_Kprice_range', 'kosts', ['Kprice_range'], unique=False)
    op.create_index('ix_kosts_Kprice', 'kosts', ['Kprice'], unique=False)
    op.drop_index(op.f('ix_kosts_Ktype'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kprice'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kprice_range'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kname'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kaddress'), table_name='kosts')
    # ### end Alembic commands ###
