"""empty message

Revision ID: 6d1d1736f132
Revises: 118de36b592b
Create Date: 2018-01-02 05:55:07.811717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d1d1736f132'
down_revision = '118de36b592b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('Cid', sa.Integer(), nullable=False))
    op.drop_index('ix_cities_kecamatan', table_name='cities')
    op.drop_column('cities', 'kecamatan')
    op.drop_column('cities', 'postal_code')
    op.add_column('kosts', sa.Column('city_Cid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_kosts_Kaddress'), 'kosts', ['Kaddress'], unique=False)
    op.create_index(op.f('ix_kosts_Kname'), 'kosts', ['Kname'], unique=False)
    op.drop_index('ix_kosts_Kaddress', table_name='kosts')
    op.drop_index('ix_kosts_Kname', table_name='kosts')
    op.drop_constraint(u'kosts_ibfk_1', 'kosts', type_='foreignkey')
    op.create_foreign_key(None, 'kosts', 'cities', ['city_Cid'], ['Cid'])
    op.drop_column('kosts', 'city_postal_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kosts', sa.Column('city_postal_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'kosts', type_='foreignkey')
    op.create_foreign_key(u'kosts_ibfk_1', 'kosts', 'cities', ['city_postal_code'], ['postal_code'])
    op.create_index('ix_kosts_Kname', 'kosts', ['Kname'], unique=False)
    op.create_index('ix_kosts_Kaddress', 'kosts', ['Kaddress'], unique=False)
    op.drop_index(op.f('ix_kosts_Kname'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kaddress'), table_name='kosts')
    op.drop_column('kosts', 'city_Cid')
    op.add_column('cities', sa.Column('postal_code', mysql.INTEGER(display_width=11), nullable=False))
    op.add_column('cities', sa.Column('kecamatan', mysql.VARCHAR(length=60), nullable=True))
    op.create_index('ix_cities_kecamatan', 'cities', ['kecamatan'], unique=False)
    op.drop_column('cities', 'Cid')
    # ### end Alembic commands ###
