"""empty message

Revision ID: b0bdf797d016
Revises: afbc62f1e060
Create Date: 2018-01-23 13:24:18.016986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0bdf797d016'
down_revision = 'afbc62f1e060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_kosts_Kaddress'), 'kosts', ['Kaddress'], unique=False)
    op.create_index(op.f('ix_kosts_Kname'), 'kosts', ['Kname'], unique=False)
    op.create_index(op.f('ix_kosts_Kprice_range'), 'kosts', ['Kprice_range'], unique=False)
    op.create_index(op.f('ix_kosts_Kprice'), 'kosts', ['Kprice'], unique=False)
    op.create_index(op.f('ix_kosts_Ktype'), 'kosts', ['Ktype'], unique=False)
    op.drop_index('ix_kosts_Kaddress', table_name='kosts')
    op.drop_index('ix_kosts_Kname', table_name='kosts')
    op.create_foreign_key(None, 'kosts', 'cities', ['city_Cid'], ['Cid'])
    op.add_column('users', sa.Column('kota_Cid', sa.Integer(), nullable=True))
    op.drop_index('ix_users_kota', table_name='users')
    op.create_foreign_key(None, 'users', 'cities', ['kota_Cid'], ['Cid'])
    op.drop_column('users', 'kota')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kota', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('ix_users_kota', 'users', ['kota'], unique=False)
    op.drop_column('users', 'kota_Cid')
    op.drop_constraint(None, 'kosts', type_='foreignkey')
    op.create_index('ix_kosts_Kname', 'kosts', ['Kname'], unique=False)
    op.create_index('ix_kosts_Kaddress', 'kosts', ['Kaddress'], unique=False)
    op.drop_index(op.f('ix_kosts_Ktype'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kprice'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kprice_range'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kname'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kaddress'), table_name='kosts')
    # ### end Alembic commands ###
