"""empty message

Revision ID: c762236eabcc
Revises: 10dc72b15ef8
Create Date: 2018-01-02 08:02:00.634567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c762236eabcc'
down_revision = '10dc72b15ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kosts', sa.Column('Kprice', sa.Integer(), nullable=True))
    op.add_column('kosts', sa.Column('Ktype', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_kosts_Kaddress'), 'kosts', ['Kaddress'], unique=False)
    op.create_index(op.f('ix_kosts_Kname'), 'kosts', ['Kname'], unique=False)
    op.create_index(op.f('ix_kosts_Kprice'), 'kosts', ['Kprice'], unique=False)
    op.create_index(op.f('ix_kosts_Ktype'), 'kosts', ['Ktype'], unique=False)
    op.drop_index('ix_kosts_Kaddress', table_name='kosts')
    op.drop_index('ix_kosts_Kname', table_name='kosts')
    op.create_foreign_key(None, 'kosts', 'cities', ['city_Cid'], ['Cid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kosts', type_='foreignkey')
    op.create_index('ix_kosts_Kname', 'kosts', ['Kname'], unique=False)
    op.create_index('ix_kosts_Kaddress', 'kosts', ['Kaddress'], unique=False)
    op.drop_index(op.f('ix_kosts_Ktype'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kprice'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kname'), table_name='kosts')
    op.drop_index(op.f('ix_kosts_Kaddress'), table_name='kosts')
    op.drop_column('kosts', 'Ktype')
    op.drop_column('kosts', 'Kprice')
    # ### end Alembic commands ###
